[package]
name = "derive-box-dyn"
version = "0.1.0"
edition = "2021"
exclude = ["/.github", ".*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2.0.53", features = ["full"] }


[lib]
proc-macro = true
