name: Test

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
  check-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        find . -type f
    - name: Check tag
      uses: ./.github/workflows/tag.yml
      with:
        push-tag: false

